### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by xmsandtoes** [akolishchak/doom-net-pytorch#1]
This is awesome! 
I am new to all of this but trying to learn as i go, so far i have vizdoom + dependencies installed and the theano, pytorch and tensorflow examples (that came included with vizdoom) all work. 

sorry for such a basic question, but how do i install this into vizdoom?

Thank you very much, any help would be greatly appreciated.

**Comment by akolishchak** [comment]
If vizdoom and pytorch with cuda are installed, you just need to clone this repo and launch the scripts:
git clone https://github.com/akolishchak/doom-net-pytorch.git
cd doom-net-pytorch
experiments/basic_aac.sh train

when training completes, check the result:
experiments/basic_aac.sh test

'experiments' directory contains scripts for several doom maps.

**Comment by xmsandtoes** [comment]
thank you for the response, i followed the instructions but i am getting a few errors.

xms@xms-G75VW:~/AI_Projects/ViZDoom/doom-net-pytorch$ experiments/basic_aac.sh train
Traceback (most recent call last):
  File "/home/xms/AI_Projects/ViZDoom/doom-net-pytorch/src/main.py", line 8, in <module>
    from model_utils import get_model
  File "/home/xms/AI_Projects/ViZDoom/doom-net-pytorch/src/model_utils.py", line 10, in <module>
    from aac import AdvantageActorCritic
  File "/home/xms/AI_Projects/ViZDoom/doom-net-pytorch/src/aac.py", line 10, in <module>
    from aac_base import AACBase
  File "/home/xms/AI_Projects/ViZDoom/doom-net-pytorch/src/aac_base.py", line 11, in <module>
    from doom_instance import *
  File "/home/xms/AI_Projects/ViZDoom/doom-net-pytorch/src/doom_instance.py", line 223
    screen = np.zeros([5, *state.screen_buffer.shape[1:]])
                          ^
SyntaxError: invalid syntax

**Comment by akolishchak** [comment]
Perhaps you use python 2.x, right?
python --version

Python 3.x is required - and python 3 versions of vizdoom and pytorch should be installed.

**Comment by xmsandtoes** [comment]
I have checked the version and you are correct, i will reinstall it all and try again.

Thank you very much for your help, i really appreciate it.

**Comment by xmsandtoes** [comment]
I managed to get it working! thank you very much for your help.


So i decided to start fresh with a new installation of ubuntu 16.04, after getting python 3, and python 3 versions of everything installed, the vizdoom example for pytorch (learning_pytorch.py) would run the example as long as i run it under "python3 learning_pytorch.py" but gave errors if i tried to run it as "python learning_python.py", so i knew it was working and finding the modules ok, but when i tried your scripts they would give an error that torch module was not found, if i installed torch again, it would break it even more and then the vizdoom examples wouldn't find the torch modules either.

changing "PYTHON" to "PYTHON3" in the basic_acc.sh script got me to a can't find "tk module" error which was fixed with: "sudo apt-get install python3-tk"

This then got me to a "not enough memory" error, which went away when i changed the batch sizes in the script from 20 to 10.

I'm guessing the memory error would have been avoided if i had installed the cpu version instead of gpu, or if i was on a desktop with a decent gpu, so if anyone else is doing this on a laptop just because you can install the gpu version doesn't mean you should.

If anyone else is trying this on ubuntu 16.04 with cuda 9.1 and python 3...
Pytorch will install with pip3 (as recommended in the official instructions) but the same instructions tell you to also install torchvision with pip3, which results in an error message telling you to install with miniconda instead, this works to install torch vision but broke vizdoom too. Instead of installing with miniconda, follow the instructions to install pytorch with pip3 and then instead of doing "pip3 install torchvision", use "pip3 install --no-dependencies torchvision".

**Comment by akolishchak** [comment]
Thanks for letting know!

I prefer anaconda python.

**Comment by xmsandtoes** [comment]
Thank you, i will try anaconda instead next time.

Here are the last 5 results from basic_aac.sh train, the mean_return shows improvement, but should the grads_norm and weights_norm always stay at 0.000000?

495: mean_return = 72.600000, grads_norm = 0.000000, weights_norm = 0.000000, batch_time = 0.864
496: mean_return = 56.600000, grads_norm = 0.000000, weights_norm = 0.000000, batch_time = 0.841
497: mean_return = 65.800000, grads_norm = 0.000000, weights_norm = 0.000000, batch_time = 0.838
498: mean_return = 49.400000, grads_norm = 0.000000, weights_norm = 0.000000, batch_time = 0.831
499: mean_return = 79.800000, grads_norm = 0.000000, weights_norm = 0.000000, batch_time = 0.844

**Comment by akolishchak** [comment]
The code had norm reporting disabled. I just fixed it. Thanks.
