### ISSUE TITLE
No module named doom_instance_map

### ISSUE THREAD

**Issue by yhcao6** [akolishchak/doom-net-pytorch#2]
where is the doom_instance_map.py file, can't find this file

**Comment by akolishchak** [comment]
Thanks for pointing it, just committed the fix.

**Comment by yhcao6** [comment]
Thanks, I just also comment the prefix and run successfully. 
Could I ask how to run experiment for D3 Battle scenario, thanks!

**Comment by yhcao6** [comment]
I look up the experiment directory and don't find script for D3 battle, could I just modify the basic_aac.sh to run D3 Battle, do I need to modify some other parameters?

Thanks!

**Comment by akolishchak** [comment]
Yes, this modification should work:
CHECK_POINT=$BASEDIR/checkpoints/d3_aac_cp.pth
CONFIG=$BASEDIR/environments/D3_battle.cfg

**Comment by akolishchak** [comment]
and increase number of training episodes:
--episode_num 5000
or even more.

**Comment by yhcao6** [comment]
I am training it!

Really thanks to you!

**Comment by yhcao6** [comment]
I trained for 5000 episodes, but the mean return doesn't increase at all.
Scenario is D3 Battle.

**Comment by akolishchak** [comment]
The magnitude of D3's reward (0..1)  is insufficient. You may correct it by modifying doom_instance.py as:
def step_normalized(self, action):
        state, reward, finished, dead = self.step(action)
        reward *= 100
        state = self.normalize(state)
        return state, reward, finished

In D3 the reward is granted only for eliminating an enemy. You could also adjust reward by including health and ammo via inheriting DoomInstance and overriding step_normalized() method, see doom_instance_cig.py (don't use it for D3, create a new one).

I have committed d3_acc.sh and D3_battle.cfg updates.
