### ISSUE TITLE
Did your imitation_lstm work?

### ISSUE THREAD

**Issue by avijit9** [akolishchak/doom-net-pytorch#4]
Hi,

Just wanted know to know if you were able to train Behavioral cloning  +  LSTM model successfully? For me, I am not able to train it.

**Comment by akolishchak** [comment]
Yes it works very well for cig. What is your environment?

**Comment by avijit9** [comment]
Hi, I'm using the D3_battle scenario. For me the avg. reward at the end of an episode is around 5-10. What about you? Do you have any plot/table to compare different methods?
