### ISSUE TITLE
Demonstration Data:

### ISSUE THREAD

**Issue by xkianteb** [akolishchak/doom-net-pytorch#6]
I am trying to run the imitation learning code in this repo, but "test/datasets/vizdoom/cig_map02/flat.h5" is not in this repo. Could you please share the demonstration data you used when running behavior cloning.

--- Thanks Kianté

**Comment by akolishchak** [comment]
Sorry, I would not share it, the file is too big for github. You may create your own, check imitation.py.

**Comment by xkianteb** [comment]
Is the demonstration data generated from human versus human games? or bot vs bot? or human versus bot?

**Comment by akolishchak** [comment]
Demonstrations generated by a human - I played myself about a hundred games and recorded data by doom_recorder_cig.py, and results merged by doom_dataset.py
